<?php
################################################################################
# Массив данных по странам и их кодам разного вида
################################################################################
Glob::$vars['country_info'] = array(
    "абхазия" =>  array("name"=>"Абхазия", "phone"=>"7 840", "kode2"=>"AB", "kode3"=>"ABH", "nkode"=>"895", "ean1"=>"", "ean2"=>"", "olimp"=>"-", "fut"=>"-",),
    "австралия" =>  array("name"=>"Австралия", "phone"=>"61", "kode2"=>"AU", "kode3"=>"AUS", "nkode"=>"36", "ean1"=>"930", "ean2"=>"939", "olimp"=>"AUS", "fut"=>"AUS",),
    "австрия" =>  array("name"=>"Австрия", "phone"=>"43", "kode2"=>"AT", "kode3"=>"AUT", "nkode"=>"40", "ean1"=>"900", "ean2"=>"919", "olimp"=>"AUT", "fut"=>"AUT",),
    "азербайджан" =>  array("name"=>"Азербайджан", "phone"=>"994", "kode2"=>"AZ", "kode3"=>"AZE", "nkode"=>"31", "ean1"=>"476", "ean2"=>"476", "olimp"=>"AZE", "fut"=>"AZE",),
    "албания" =>  array("name"=>"Албания", "phone"=>"355", "kode2"=>"AL", "kode3"=>"ALB", "nkode"=>"8", "ean1"=>"530", "ean2"=>"530", "olimp"=>"ALB", "fut"=>"ALB",),
    "алжир" =>  array("name"=>"Алжир", "phone"=>"213", "kode2"=>"DZ", "kode3"=>"DZA", "nkode"=>"12", "ean1"=>"613", "ean2"=>"613", "olimp"=>"ALG", "fut"=>"ALG",),
    "ангола" =>  array("name"=>"Ангола", "phone"=>"244", "kode2"=>"AO", "kode3"=>"AGO", "nkode"=>"24", "ean1"=>"", "ean2"=>"", "olimp"=>"ANG", "fut"=>"ANG",),
    "андорра" =>  array("name"=>"Андорра", "phone"=>"376", "kode2"=>"AD", "kode3"=>"AND", "nkode"=>"20", "ean1"=>"", "ean2"=>"", "olimp"=>"AND", "fut"=>"AND",),
    "антигуа и барбуда" =>  array("name"=>"Антигуа и Барбуда", "phone"=>"1 268", "kode2"=>"AG", "kode3"=>"ATG", "nkode"=>"28", "ean1"=>"", "ean2"=>"", "olimp"=>"ANT", "fut"=>"ATG",),
    "аргентина" =>  array("name"=>"Аргентина", "phone"=>"54", "kode2"=>"AR", "kode3"=>"ARG", "nkode"=>"32", "ean1"=>"779", "ean2"=>"779", "olimp"=>"ARG", "fut"=>"ARG",),
    "армения" =>  array("name"=>"Армения", "phone"=>"374", "kode2"=>"AM", "kode3"=>"ARM", "nkode"=>"51", "ean1"=>"485", "ean2"=>"485", "olimp"=>"ARM", "fut"=>"ARM",),
    "афганистан" =>  array("name"=>"Афганистан", "phone"=>"93", "kode2"=>"AF", "kode3"=>"AFG", "nkode"=>"4", "ean1"=>"", "ean2"=>"", "olimp"=>"AFG", "fut"=>"AFG",),
    "багамские острова" =>  array("name"=>"Багамские Острова", "phone"=>"1 242", "kode2"=>"BS", "kode3"=>"BHS", "nkode"=>"44", "ean1"=>"", "ean2"=>"", "olimp"=>"BAH", "fut"=>"BAH",),
    "бангладеш" =>  array("name"=>"Бангладеш", "phone"=>"880", "kode2"=>"BD", "kode3"=>"BGD", "nkode"=>"50", "ean1"=>"", "ean2"=>"", "olimp"=>"BAN", "fut"=>"BAN",),
    "барбадос" =>  array("name"=>"Барбадос", "phone"=>"1 246", "kode2"=>"BB", "kode3"=>"BRB", "nkode"=>"52", "ean1"=>"", "ean2"=>"", "olimp"=>"BAR", "fut"=>"BRB",),
    "бахрейн" =>  array("name"=>"Бахрейн", "phone"=>"973", "kode2"=>"BH", "kode3"=>"BHR", "nkode"=>"48", "ean1"=>"608", "ean2"=>"608", "olimp"=>"BRN", "fut"=>"BHR",),
    "белиз" =>  array("name"=>"Белиз", "phone"=>"501", "kode2"=>"BZ", "kode3"=>"BLZ", "nkode"=>"84", "ean1"=>"", "ean2"=>"", "olimp"=>"BIZ", "fut"=>"BLZ",),
    "белоруссия" =>  array("name"=>"Белоруссия", "phone"=>"375", "kode2"=>"BY", "kode3"=>"BLR", "nkode"=>"112", "ean1"=>"481", "ean2"=>"481", "olimp"=>"BLR", "fut"=>"BLR",),
    "беларуссия" =>  array("name"=>"Белоруссия", "phone"=>"375", "kode2"=>"BY", "kode3"=>"BLR", "nkode"=>"112", "ean1"=>"481", "ean2"=>"481", "olimp"=>"BLR", "fut"=>"BLR",),
    "беларусь" =>  array("name"=>"Белоруссия", "phone"=>"375", "kode2"=>"BY", "kode3"=>"BLR", "nkode"=>"112", "ean1"=>"481", "ean2"=>"481", "olimp"=>"BLR", "fut"=>"BLR",),
    "бельгия" =>  array("name"=>"Бельгия", "phone"=>"32", "kode2"=>"BE", "kode3"=>"BEL", "nkode"=>"56", "ean1"=>"540", "ean2"=>"549", "olimp"=>"BEL", "fut"=>"BEL",),
    "бенин" =>  array("name"=>"Бенин", "phone"=>"229", "kode2"=>"BJ", "kode3"=>"BEN", "nkode"=>"204", "ean1"=>"", "ean2"=>"", "olimp"=>"BEN", "fut"=>"BEN",),
    "болгария" =>  array("name"=>"Болгария", "phone"=>"359", "kode2"=>"BG", "kode3"=>"BGR", "nkode"=>"100", "ean1"=>"380", "ean2"=>"380", "olimp"=>"BUL", "fut"=>"BUL",),
    "боливия" =>  array("name"=>"Боливия", "phone"=>"591", "kode2"=>"BO", "kode3"=>"BOL", "nkode"=>"68", "ean1"=>"777", "ean2"=>"777", "olimp"=>"BOL", "fut"=>"BOL",),
    "босния и герцеговина" =>  array("name"=>"Босния и Герцеговина", "phone"=>"387", "kode2"=>"BA", "kode3"=>"BIH", "nkode"=>"70", "ean1"=>"387", "ean2"=>"387", "olimp"=>"BIH", "fut"=>"BIH",),
    "ботсвана" =>  array("name"=>"Ботсвана", "phone"=>"267", "kode2"=>"BW", "kode3"=>"BWA", "nkode"=>"72", "ean1"=>"", "ean2"=>"", "olimp"=>"BOT", "fut"=>"BOT",),
    "бразилия" =>  array("name"=>"Бразилия", "phone"=>"55", "kode2"=>"BR", "kode3"=>"BRA", "nkode"=>"76", "ean1"=>"789", "ean2"=>"790", "olimp"=>"BRA", "fut"=>"BRA",),
    "бруней" =>  array("name"=>"Бруней", "phone"=>"673", "kode2"=>"BN", "kode3"=>"BRN", "nkode"=>"96", "ean1"=>"", "ean2"=>"", "olimp"=>"BRU", "fut"=>"BRU",),
    "буркина-фасо" =>  array("name"=>"Буркина-Фасо", "phone"=>"226", "kode2"=>"BF", "kode3"=>"BFA", "nkode"=>"854", "ean1"=>"", "ean2"=>"", "olimp"=>"BUR", "fut"=>"BFA",),
    "бурунди" =>  array("name"=>"Бурунди", "phone"=>"257", "kode2"=>"BI", "kode3"=>"BDI", "nkode"=>"108", "ean1"=>"", "ean2"=>"", "olimp"=>"BDI", "fut"=>"BDI",),
    "бутан" =>  array("name"=>"Бутан", "phone"=>"975", "kode2"=>"BT", "kode3"=>"BTN", "nkode"=>"64", "ean1"=>"", "ean2"=>"", "olimp"=>"BHU", "fut"=>"BHU",),
    "вануату" =>  array("name"=>"Вануату", "phone"=>"678", "kode2"=>"VU", "kode3"=>"VUT", "nkode"=>"548", "ean1"=>"", "ean2"=>"", "olimp"=>"VAN", "fut"=>"VAN",),
    "ватикан" =>  array("name"=>"Ватикан", "phone"=>"379", "kode2"=>"VA", "kode3"=>"VAT", "nkode"=>"336", "ean1"=>"", "ean2"=>"", "olimp"=>"-", "fut"=>"-",),
    "великобритания" =>  array("name"=>"Великобритания", "phone"=>"44", "kode2"=>"GB", "kode3"=>"GBR", "nkode"=>"826", "ean1"=>"500", "ean2"=>"509", "olimp"=>"GBR", "fut"=>"-",),
    "венгрия" =>  array("name"=>"Венгрия", "phone"=>"36", "kode2"=>"HU", "kode3"=>"HUN", "nkode"=>"348", "ean1"=>"599", "ean2"=>"599", "olimp"=>"HUN", "fut"=>"HUN",),
    "венесуэла" =>  array("name"=>"Венесуэла", "phone"=>"58", "kode2"=>"VE", "kode3"=>"VEN", "nkode"=>"862", "ean1"=>"759", "ean2"=>"759", "olimp"=>"VEN", "fut"=>"VEN",),
    "восточный тимор" =>  array("name"=>"Восточный Тимор", "phone"=>"670", "kode2"=>"TL", "kode3"=>"TLS", "nkode"=>"626", "ean1"=>"", "ean2"=>"", "olimp"=>"TLS", "fut"=>"TLS",),
    "вьетнам" =>  array("name"=>"Вьетнам", "phone"=>"84", "kode2"=>"VN", "kode3"=>"VNM", "nkode"=>"704", "ean1"=>"893", "ean2"=>"893", "olimp"=>"VIE", "fut"=>"VIE",),
    "габон" =>  array("name"=>"Габон", "phone"=>"241", "kode2"=>"GA", "kode3"=>"GAB", "nkode"=>"266", "ean1"=>"", "ean2"=>"", "olimp"=>"GAB", "fut"=>"GAB",),
    "гаити" =>  array("name"=>"Гаити", "phone"=>"509", "kode2"=>"HT", "kode3"=>"HTI", "nkode"=>"332", "ean1"=>"", "ean2"=>"", "olimp"=>"HAI", "fut"=>"HAI",),
    "гайана" =>  array("name"=>"Гайана", "phone"=>"592", "kode2"=>"GY", "kode3"=>"GUY", "nkode"=>"328", "ean1"=>"", "ean2"=>"", "olimp"=>"GUY", "fut"=>"GUY",),
    "гамбия" =>  array("name"=>"Гамбия", "phone"=>"220", "kode2"=>"GM", "kode3"=>"GMB", "nkode"=>"270", "ean1"=>"", "ean2"=>"", "olimp"=>"GAM", "fut"=>"GAM",),
    "гана" =>  array("name"=>"Гана", "phone"=>"233", "kode2"=>"GH", "kode3"=>"GHA", "nkode"=>"288", "ean1"=>"603", "ean2"=>"603", "olimp"=>"GHA", "fut"=>"GHA",),
    "гватемала" =>  array("name"=>"Гватемала", "phone"=>"502", "kode2"=>"GT", "kode3"=>"GTM", "nkode"=>"320", "ean1"=>"740", "ean2"=>"740", "olimp"=>"GUA", "fut"=>"GUA",),
    "гвинея" =>  array("name"=>"Гвинея", "phone"=>"224", "kode2"=>"GN", "kode3"=>"GIN", "nkode"=>"324", "ean1"=>"", "ean2"=>"", "olimp"=>"GUI", "fut"=>"GUI",),
    "гвинея-бисау" =>  array("name"=>"Гвинея-Бисау", "phone"=>"245", "kode2"=>"GW", "kode3"=>"GNB", "nkode"=>"624", "ean1"=>"", "ean2"=>"", "olimp"=>"GBS", "fut"=>"GNB",),
    "германия" =>  array("name"=>"Германия", "phone"=>"49", "kode2"=>"DE", "kode3"=>"DEU", "nkode"=>"276", "ean1"=>"400", "ean2"=>"440", "olimp"=>"GER", "fut"=>"GER",),
    "гондурас" =>  array("name"=>"Гондурас", "phone"=>"504", "kode2"=>"HN", "kode3"=>"HND", "nkode"=>"340", "ean1"=>"742", "ean2"=>"742", "olimp"=>"HON", "fut"=>"HON",),
    "государство палестина" =>  array("name"=>"Государство Палестина", "phone"=>"970", "kode2"=>"PS", "kode3"=>"PSE", "nkode"=>"275", "ean1"=>"", "ean2"=>"", "olimp"=>"PLE", "fut"=>"PLE",),
    "гренада" =>  array("name"=>"Гренада", "phone"=>"1 473", "kode2"=>"GD", "kode3"=>"GRD", "nkode"=>"308", "ean1"=>"", "ean2"=>"", "olimp"=>"GRN", "fut"=>"GRN",),
    "греция" =>  array("name"=>"Греция", "phone"=>"30", "kode2"=>"GR", "kode3"=>"GRC", "nkode"=>"300", "ean1"=>"520", "ean2"=>"520", "olimp"=>"GRE", "fut"=>"GRE",),
    "грузия" =>  array("name"=>"Грузия", "phone"=>"995", "kode2"=>"GE", "kode3"=>"GEO", "nkode"=>"268", "ean1"=>"486", "ean2"=>"486", "olimp"=>"GEO", "fut"=>"GEO",),
    "дания" =>  array("name"=>"Дания", "phone"=>"45", "kode2"=>"DK", "kode3"=>"DNK", "nkode"=>"208", "ean1"=>"570", "ean2"=>"579", "olimp"=>"DEN", "fut"=>"DEN",),
    "джибути" =>  array("name"=>"Джибути", "phone"=>"253", "kode2"=>"DJ", "kode3"=>"DJI", "nkode"=>"262", "ean1"=>"", "ean2"=>"", "olimp"=>"DJI", "fut"=>"DJI",),
    "доминика" =>  array("name"=>"Доминика", "phone"=>"1 767", "kode2"=>"DM", "kode3"=>"DMA", "nkode"=>"212", "ean1"=>"", "ean2"=>"", "olimp"=>"DMA", "fut"=>"DMA",),
    "доминиканская республика" =>  array("name"=>"Доминиканская Республика", "phone"=>"1 809", "kode2"=>"DO", "kode3"=>"DOM", "nkode"=>"214", "ean1"=>"746", "ean2"=>"746", "olimp"=>"DOM", "fut"=>"DOM",),
    "др конго" =>  array("name"=>"ДР Конго", "phone"=>"243", "kode2"=>"CD", "kode3"=>"COD", "nkode"=>"180", "ean1"=>"", "ean2"=>"", "olimp"=>"COD", "fut"=>"COD",),
    "египет" =>  array("name"=>"Египет", "phone"=>"20", "kode2"=>"EG", "kode3"=>"EGY", "nkode"=>"818", "ean1"=>"622", "ean2"=>"622", "olimp"=>"EGY", "fut"=>"EGY",),
    "замбия" =>  array("name"=>"Замбия", "phone"=>"260", "kode2"=>"ZM", "kode3"=>"ZMB", "nkode"=>"894", "ean1"=>"", "ean2"=>"", "olimp"=>"ZAM", "fut"=>"ZAM",),
    "зимбабве" =>  array("name"=>"Зимбабве", "phone"=>"263", "kode2"=>"ZW", "kode3"=>"ZWE", "nkode"=>"716", "ean1"=>"", "ean2"=>"", "olimp"=>"ZIM", "fut"=>"ZIM",),
    "израиль" =>  array("name"=>"Израиль", "phone"=>"972", "kode2"=>"IL", "kode3"=>"ISR", "nkode"=>"376", "ean1"=>"729", "ean2"=>"729", "olimp"=>"ISR", "fut"=>"ISR",),
    "индия" =>  array("name"=>"Индия", "phone"=>"91", "kode2"=>"IN", "kode3"=>"IND", "nkode"=>"356", "ean1"=>"890", "ean2"=>"890", "olimp"=>"IND", "fut"=>"IND",),
    "индонезия" =>  array("name"=>"Индонезия", "phone"=>"62", "kode2"=>"ID", "kode3"=>"IDN", "nkode"=>"360", "ean1"=>"899", "ean2"=>"899", "olimp"=>"INA", "fut"=>"IDN",),
    "иордания" =>  array("name"=>"Иордания", "phone"=>"962", "kode2"=>"JO", "kode3"=>"JOR", "nkode"=>"400", "ean1"=>"625", "ean2"=>"625", "olimp"=>"JOR", "fut"=>"JOR",),
    "ирак" =>  array("name"=>"Ирак", "phone"=>"964", "kode2"=>"IQ", "kode3"=>"IRQ", "nkode"=>"368", "ean1"=>"", "ean2"=>"", "olimp"=>"IRQ", "fut"=>"IRQ",),
    "иран" =>  array("name"=>"Иран", "phone"=>"98", "kode2"=>"IR", "kode3"=>"IRN", "nkode"=>"364", "ean1"=>"626", "ean2"=>"626", "olimp"=>"IRI", "fut"=>"IRN",),
    "ирландия" =>  array("name"=>"Ирландия", "phone"=>"353", "kode2"=>"IE", "kode3"=>"IRL", "nkode"=>"372", "ean1"=>"539", "ean2"=>"539", "olimp"=>"IRL", "fut"=>"IRL",),
    "исландия" =>  array("name"=>"Исландия", "phone"=>"354", "kode2"=>"IS", "kode3"=>"ISL", "nkode"=>"352", "ean1"=>"569", "ean2"=>"569", "olimp"=>"ISL", "fut"=>"ISL",),
    "испания" =>  array("name"=>"Испания", "phone"=>"34", "kode2"=>"ES", "kode3"=>"ESP", "nkode"=>"724", "ean1"=>"840", "ean2"=>"849", "olimp"=>"ESP", "fut"=>"ESP",),
    "италия" =>  array("name"=>"Италия", "phone"=>"39", "kode2"=>"IT", "kode3"=>"ITA", "nkode"=>"380", "ean1"=>"800", "ean2"=>"839", "olimp"=>"ITA", "fut"=>"ITA",),
    "йемен" =>  array("name"=>"Йемен", "phone"=>"967", "kode2"=>"YE", "kode3"=>"YEM", "nkode"=>"887", "ean1"=>"", "ean2"=>"", "olimp"=>"YEM", "fut"=>"YEM",),
    "кабо-верде" =>  array("name"=>"Кабо-Верде", "phone"=>"238", "kode2"=>"CV", "kode3"=>"CPV", "nkode"=>"132", "ean1"=>"", "ean2"=>"", "olimp"=>"CPV", "fut"=>"CPV",),
    "казахстан" =>  array("name"=>"Казахстан", "phone"=>"+7 xxx", "kode2"=>"KZ", "kode3"=>"KAZ", "nkode"=>"398", "ean1"=>"487", "ean2"=>"487", "olimp"=>"KAZ", "fut"=>"KAZ",),
    "камбоджа" =>  array("name"=>"Камбоджа", "phone"=>"855", "kode2"=>"KH", "kode3"=>"KHM", "nkode"=>"116", "ean1"=>"884", "ean2"=>"884", "olimp"=>"CAM", "fut"=>"CAM",),
    "камерун" =>  array("name"=>"Камерун", "phone"=>"237", "kode2"=>"CM", "kode3"=>"CMR", "nkode"=>"120", "ean1"=>"", "ean2"=>"", "olimp"=>"CMR", "fut"=>"CMR",),
    "канада" =>  array("name"=>"Канада", "phone"=>"+1 xxx", "kode2"=>"CA", "kode3"=>"CAN", "nkode"=>"124", "ean1"=>"754", "ean2"=>"755", "olimp"=>"CAN", "fut"=>"CAN",),
    "катар" =>  array("name"=>"Катар", "phone"=>"974", "kode2"=>"QA", "kode3"=>"QAT", "nkode"=>"634", "ean1"=>"", "ean2"=>"", "olimp"=>"QAT", "fut"=>"QAT",),
    "кения" =>  array("name"=>"Кения", "phone"=>"254", "kode2"=>"KE", "kode3"=>"KEN", "nkode"=>"404", "ean1"=>"616", "ean2"=>"616", "olimp"=>"KEN", "fut"=>"KEN",),
    "кипр" =>  array("name"=>"Кипр", "phone"=>"357", "kode2"=>"CY", "kode3"=>"CYP", "nkode"=>"196", "ean1"=>"529", "ean2"=>"529", "olimp"=>"CYP", "fut"=>"CYP",),
    "киргизия" =>  array("name"=>"Киргизия", "phone"=>"996", "kode2"=>"KG", "kode3"=>"KGZ", "nkode"=>"417", "ean1"=>"470", "ean2"=>"470", "olimp"=>"KGZ", "fut"=>"KGZ",),
    "кирибати" =>  array("name"=>"Кирибати", "phone"=>"686", "kode2"=>"KI", "kode3"=>"KIR", "nkode"=>"296", "ean1"=>"", "ean2"=>"", "olimp"=>"KIR", "fut"=>"-",),
    "китай" =>  array("name"=>"Китай", "phone"=>"86", "kode2"=>"CN", "kode3"=>"CHN", "nkode"=>"156", "ean1"=>"690", "ean2"=>"695", "olimp"=>"CHN", "fut"=>"CHN",),
    "кндр" =>  array("name"=>"КНДР", "phone"=>"850", "kode2"=>"KP", "kode3"=>"PRK", "nkode"=>"408", "ean1"=>"867", "ean2"=>"867", "olimp"=>"PRK", "fut"=>"PRK",),
    "колумбия" =>  array("name"=>"Колумбия", "phone"=>"57", "kode2"=>"CO", "kode3"=>"COL", "nkode"=>"170", "ean1"=>"770", "ean2"=>"770", "olimp"=>"COL", "fut"=>"COL",),
    "коморские острова" =>  array("name"=>"Коморские Острова", "phone"=>"269", "kode2"=>"KM", "kode3"=>"COM", "nkode"=>"174", "ean1"=>"", "ean2"=>"", "olimp"=>"COM", "fut"=>"COM",),
    "коста-рика" =>  array("name"=>"Коста-Рика", "phone"=>"506", "kode2"=>"CR", "kode3"=>"CRI", "nkode"=>"188", "ean1"=>"744", "ean2"=>"744", "olimp"=>"CRC", "fut"=>"CRC",),
    "кот-дивуар" =>  array("name"=>"Кот-дИвуар", "phone"=>"225", "kode2"=>"CI", "kode3"=>"CIV", "nkode"=>"384", "ean1"=>"618", "ean2"=>"618", "olimp"=>"CIV", "fut"=>"CIV",),
    "куба" =>  array("name"=>"Куба", "phone"=>"53", "kode2"=>"CU", "kode3"=>"CUB", "nkode"=>"192", "ean1"=>"850", "ean2"=>"850", "olimp"=>"CUB", "fut"=>"CUB",),
    "кувейт" =>  array("name"=>"Кувейт", "phone"=>"965", "kode2"=>"KW", "kode3"=>"KWT", "nkode"=>"414", "ean1"=>"627", "ean2"=>"627", "olimp"=>"KUW", "fut"=>"KUW",),
    "лаос" =>  array("name"=>"Лаос", "phone"=>"856", "kode2"=>"LA", "kode3"=>"LAO", "nkode"=>"418", "ean1"=>"", "ean2"=>"", "olimp"=>"LAO", "fut"=>"LAO",),
    "латвия" =>  array("name"=>"Латвия", "phone"=>"371", "kode2"=>"LV", "kode3"=>"LVA", "nkode"=>"428", "ean1"=>"475", "ean2"=>"475", "olimp"=>"LAT", "fut"=>"LVA",),
    "лесото" =>  array("name"=>"Лесото", "phone"=>"266", "kode2"=>"LS", "kode3"=>"LSO", "nkode"=>"426", "ean1"=>"", "ean2"=>"", "olimp"=>"LES", "fut"=>"LES",),
    "либерия" =>  array("name"=>"Либерия", "phone"=>"231", "kode2"=>"LR", "kode3"=>"LBR", "nkode"=>"430", "ean1"=>"", "ean2"=>"", "olimp"=>"LBR", "fut"=>"LBR",),
    "ливан" =>  array("name"=>"Ливан", "phone"=>"961", "kode2"=>"LB", "kode3"=>"LBN", "nkode"=>"422", "ean1"=>"528", "ean2"=>"528", "olimp"=>"LIB", "fut"=>"LIB",),
    "ливия" =>  array("name"=>"Ливия", "phone"=>"218", "kode2"=>"LY", "kode3"=>"LBY", "nkode"=>"434", "ean1"=>"624", "ean2"=>"624", "olimp"=>"LBA", "fut"=>"LBY",),
    "литва" =>  array("name"=>"Литва", "phone"=>"370", "kode2"=>"LT", "kode3"=>"LTU", "nkode"=>"440", "ean1"=>"477", "ean2"=>"477", "olimp"=>"LTU", "fut"=>"LTU",),
    "лихтенштейн" =>  array("name"=>"Лихтенштейн", "phone"=>"423", "kode2"=>"LI", "kode3"=>"LIE", "nkode"=>"438", "ean1"=>"", "ean2"=>"", "olimp"=>"LIE", "fut"=>"LIE",),
    "люксембург" =>  array("name"=>"Люксембург", "phone"=>"352", "kode2"=>"LU", "kode3"=>"LUX", "nkode"=>"442", "ean1"=>"540", "ean2"=>"549", "olimp"=>"LUX", "fut"=>"LUX",),
    "маврикий" =>  array("name"=>"Маврикий", "phone"=>"230", "kode2"=>"MU", "kode3"=>"MUS", "nkode"=>"480", "ean1"=>"609", "ean2"=>"609", "olimp"=>"MRI", "fut"=>"MRI",),
    "мавритания" =>  array("name"=>"Мавритания", "phone"=>"222", "kode2"=>"MR", "kode3"=>"MRT", "nkode"=>"478", "ean1"=>"", "ean2"=>"", "olimp"=>"MTN", "fut"=>"MTN",),
    "мадагаскар" =>  array("name"=>"Мадагаскар", "phone"=>"261", "kode2"=>"MG", "kode3"=>"MDG", "nkode"=>"450", "ean1"=>"", "ean2"=>"", "olimp"=>"MAD", "fut"=>"MAD",),
    "македония" =>  array("name"=>"Македония", "phone"=>"389", "kode2"=>"MK", "kode3"=>"MKD", "nkode"=>"807", "ean1"=>"531", "ean2"=>"531", "olimp"=>"MKD", "fut"=>"MKD",),
    "малави" =>  array("name"=>"Малави", "phone"=>"265", "kode2"=>"MW", "kode3"=>"MWI", "nkode"=>"454", "ean1"=>"", "ean2"=>"", "olimp"=>"MAW", "fut"=>"MWI",),
    "малайзия" =>  array("name"=>"Малайзия", "phone"=>"60", "kode2"=>"MY", "kode3"=>"MYS", "nkode"=>"458", "ean1"=>"955", "ean2"=>"955", "olimp"=>"MAS", "fut"=>"MAS",),
    "мали" =>  array("name"=>"Мали", "phone"=>"223", "kode2"=>"ML", "kode3"=>"MLI", "nkode"=>"466", "ean1"=>"", "ean2"=>"", "olimp"=>"MLI", "fut"=>"MLI",),
    "мальдивские острова" =>  array("name"=>"Мальдивские Острова", "phone"=>"960", "kode2"=>"MV", "kode3"=>"MDV", "nkode"=>"462", "ean1"=>"", "ean2"=>"", "olimp"=>"MDV", "fut"=>"MDV",),
    "мальта" =>  array("name"=>"Мальта", "phone"=>"356", "kode2"=>"MT", "kode3"=>"MLT", "nkode"=>"470", "ean1"=>"535", "ean2"=>"535", "olimp"=>"MLT", "fut"=>"MLT",),
    "марокко" =>  array("name"=>"Марокко", "phone"=>"212", "kode2"=>"MA", "kode3"=>"MAR", "nkode"=>"504", "ean1"=>"611", "ean2"=>"611", "olimp"=>"MAR", "fut"=>"MAR",),
    "маршалловы острова" =>  array("name"=>"Маршалловы Острова", "phone"=>"692", "kode2"=>"MH", "kode3"=>"MHL", "nkode"=>"584", "ean1"=>"", "ean2"=>"", "olimp"=>"MHL", "fut"=>"-",),
    "мексика" =>  array("name"=>"Мексика", "phone"=>"52", "kode2"=>"MX", "kode3"=>"MEX", "nkode"=>"484", "ean1"=>"750", "ean2"=>"750", "olimp"=>"MEX", "fut"=>"MEX",),
    "мозамбик" =>  array("name"=>"Мозамбик", "phone"=>"258", "kode2"=>"MZ", "kode3"=>"MOZ", "nkode"=>"508", "ean1"=>"", "ean2"=>"", "olimp"=>"MOZ", "fut"=>"MOZ",),
    "молдавия" =>  array("name"=>"Молдавия", "phone"=>"373", "kode2"=>"MD", "kode3"=>"MDA", "nkode"=>"498", "ean1"=>"484", "ean2"=>"484", "olimp"=>"MDA", "fut"=>"MDA",),
    "монако" =>  array("name"=>"Монако", "phone"=>"377", "kode2"=>"MC", "kode3"=>"MCO", "nkode"=>"492", "ean1"=>"", "ean2"=>"", "olimp"=>"MON", "fut"=>"-",),
    "монголия" =>  array("name"=>"Монголия", "phone"=>"976", "kode2"=>"MN", "kode3"=>"MNG", "nkode"=>"496", "ean1"=>"865", "ean2"=>"865", "olimp"=>"MGL", "fut"=>"MGL",),
    "мьянма" =>  array("name"=>"Мьянма", "phone"=>"95", "kode2"=>"MM", "kode3"=>"MMR", "nkode"=>"104", "ean1"=>"", "ean2"=>"", "olimp"=>"MYA", "fut"=>"MYA",),
    "намибия" =>  array("name"=>"Намибия", "phone"=>"264", "kode2"=>"NA", "kode3"=>"NAM", "nkode"=>"516", "ean1"=>"", "ean2"=>"", "olimp"=>"NAM", "fut"=>"NAM",),
    "науру" =>  array("name"=>"Науру", "phone"=>"674", "kode2"=>"NR", "kode3"=>"NRU", "nkode"=>"520", "ean1"=>"", "ean2"=>"", "olimp"=>"NRU", "fut"=>"-",),
    "непал" =>  array("name"=>"Непал", "phone"=>"977", "kode2"=>"NP", "kode3"=>"NPL", "nkode"=>"524", "ean1"=>"", "ean2"=>"", "olimp"=>"NEP", "fut"=>"NEP",),
    "нигер" =>  array("name"=>"Нигер", "phone"=>"227", "kode2"=>"NE", "kode3"=>"NER", "nkode"=>"562", "ean1"=>"", "ean2"=>"", "olimp"=>"NIG", "fut"=>"NIG",),
    "нигерия" =>  array("name"=>"Нигерия", "phone"=>"234", "kode2"=>"NG", "kode3"=>"NGA", "nkode"=>"566", "ean1"=>"", "ean2"=>"", "olimp"=>"NGR", "fut"=>"NGA",),
    "нидерланды" =>  array("name"=>"Нидерланды", "phone"=>"31", "kode2"=>"NL", "kode3"=>"NLD", "nkode"=>"528", "ean1"=>"870", "ean2"=>"879", "olimp"=>"NED", "fut"=>"NED",),
    "никарагуа" =>  array("name"=>"Никарагуа", "phone"=>"505", "kode2"=>"NI", "kode3"=>"NIC", "nkode"=>"558", "ean1"=>"743", "ean2"=>"743", "olimp"=>"NCA", "fut"=>"NCA",),
    "новая зеландия" =>  array("name"=>"Новая Зеландия", "phone"=>"64", "kode2"=>"NZ", "kode3"=>"NZL", "nkode"=>"554", "ean1"=>"940", "ean2"=>"949", "olimp"=>"NZL", "fut"=>"NZL",),
    "норвегия" =>  array("name"=>"Норвегия", "phone"=>"47", "kode2"=>"NO", "kode3"=>"NOR", "nkode"=>"578", "ean1"=>"700", "ean2"=>"709", "olimp"=>"NOR", "fut"=>"NOR",),
    "оаэ" =>  array("name"=>"ОАЭ", "phone"=>"971", "kode2"=>"AE", "kode3"=>"ARE", "nkode"=>"784", "ean1"=>"629", "ean2"=>"629", "olimp"=>"UAE", "fut"=>"UAE",),
    "оман" =>  array("name"=>"Оман", "phone"=>"968", "kode2"=>"OM", "kode3"=>"OMN", "nkode"=>"512", "ean1"=>"", "ean2"=>"", "olimp"=>"OMA", "fut"=>"OMA",),
    "пакистан" =>  array("name"=>"Пакистан", "phone"=>"92", "kode2"=>"PK", "kode3"=>"PAK", "nkode"=>"586", "ean1"=>"", "ean2"=>"", "olimp"=>"PAK", "fut"=>"PAK",),
    "палау" =>  array("name"=>"Палау", "phone"=>"680", "kode2"=>"PW", "kode3"=>"PLW", "nkode"=>"585", "ean1"=>"", "ean2"=>"", "olimp"=>"PLW", "fut"=>"-",),
    "панама" =>  array("name"=>"Панама", "phone"=>"507", "kode2"=>"PA", "kode3"=>"PAN", "nkode"=>"591", "ean1"=>"745", "ean2"=>"745", "olimp"=>"PAN", "fut"=>"PAN",),
    "папуа - новая гвинея" =>  array("name"=>"Папуа - Новая Гвинея", "phone"=>"675", "kode2"=>"PG", "kode3"=>"PNG", "nkode"=>"598", "ean1"=>"", "ean2"=>"", "olimp"=>"PNG", "fut"=>"PNG",),
    "парагвай" =>  array("name"=>"Парагвай", "phone"=>"595", "kode2"=>"PY", "kode3"=>"PRY", "nkode"=>"600", "ean1"=>"784", "ean2"=>"784", "olimp"=>"PAR", "fut"=>"PAR",),
    "перу" =>  array("name"=>"Перу", "phone"=>"51", "kode2"=>"PE", "kode3"=>"PER", "nkode"=>"604", "ean1"=>"775", "ean2"=>"775", "olimp"=>"PER", "fut"=>"PER",),
    "польша" =>  array("name"=>"Польша", "phone"=>"48", "kode2"=>"PL", "kode3"=>"POL", "nkode"=>"616", "ean1"=>"590", "ean2"=>"590", "olimp"=>"POL", "fut"=>"POL",),
    "португалия" =>  array("name"=>"Португалия", "phone"=>"351", "kode2"=>"PT", "kode3"=>"PRT", "nkode"=>"620", "ean1"=>"560", "ean2"=>"560", "olimp"=>"POR", "fut"=>"POR",),
    "республика конго" =>  array("name"=>"Республика Конго", "phone"=>"242", "kode2"=>"CG", "kode3"=>"COG", "nkode"=>"178", "ean1"=>"", "ean2"=>"", "olimp"=>"CGO", "fut"=>"CGO",),
    "республика корея" =>  array("name"=>"Республика Корея", "phone"=>"82", "kode2"=>"KR", "kode3"=>"KOR", "nkode"=>"410", "ean1"=>"880", "ean2"=>"880", "olimp"=>"KOR", "fut"=>"KOR",),
    "россия" =>  array("name"=>"Россия", "phone"=>"+7 xxx", "kode2"=>"RU", "kode3"=>"RUS", "nkode"=>"643", "ean1"=>"460", "ean2"=>"469", "olimp"=>"RUS", "fut"=>"RUS",),
    "руанда" =>  array("name"=>"Руанда", "phone"=>"250", "kode2"=>"RW", "kode3"=>"RWA", "nkode"=>"646", "ean1"=>"", "ean2"=>"", "olimp"=>"RWA", "fut"=>"RWA",),
    "румыния" =>  array("name"=>"Румыния", "phone"=>"40", "kode2"=>"RO", "kode3"=>"ROU", "nkode"=>"642", "ean1"=>"594", "ean2"=>"594", "olimp"=>"ROU", "fut"=>"ROU",),
    "сальвадор" =>  array("name"=>"Сальвадор", "phone"=>"503", "kode2"=>"SV", "kode3"=>"SLV", "nkode"=>"222", "ean1"=>"741", "ean2"=>"741", "olimp"=>"ESA", "fut"=>"SLV",),
    "самоа" =>  array("name"=>"Самоа", "phone"=>"685", "kode2"=>"WS", "kode3"=>"WSM", "nkode"=>"882", "ean1"=>"", "ean2"=>"", "olimp"=>"SAM", "fut"=>"SAM",),
    "сан-марино" =>  array("name"=>"Сан-Марино", "phone"=>"378", "kode2"=>"SM", "kode3"=>"SMR", "nkode"=>"674", "ean1"=>"", "ean2"=>"", "olimp"=>"SMR", "fut"=>"SMR",),
    "сан-томе и принсипи" =>  array("name"=>"Сан-Томе и Принсипи", "phone"=>"239", "kode2"=>"ST", "kode3"=>"STP", "nkode"=>"678", "ean1"=>"", "ean2"=>"", "olimp"=>"STP", "fut"=>"STP",),
    "саудовская аравия" =>  array("name"=>"Саудовская Аравия", "phone"=>"966", "kode2"=>"SA", "kode3"=>"SAU", "nkode"=>"682", "ean1"=>"628", "ean2"=>"628", "olimp"=>"KSA", "fut"=>"KSA",),
    "свазиленд" =>  array("name"=>"Свазиленд", "phone"=>"268", "kode2"=>"SZ", "kode3"=>"SWZ", "nkode"=>"748", "ean1"=>"", "ean2"=>"", "olimp"=>"SWZ", "fut"=>"SWZ",),
    "сейшельские острова" =>  array("name"=>"Сейшельские Острова", "phone"=>"248", "kode2"=>"SC", "kode3"=>"SYC", "nkode"=>"690", "ean1"=>"", "ean2"=>"", "olimp"=>"SEY", "fut"=>"SEY",),
    "сенегал" =>  array("name"=>"Сенегал", "phone"=>"221", "kode2"=>"SN", "kode3"=>"SEN", "nkode"=>"686", "ean1"=>"", "ean2"=>"", "olimp"=>"SEN", "fut"=>"SEN",),
    "сент-винсент и гренадины" =>  array("name"=>"Сент-Винсент и Гренадины", "phone"=>"1 784", "kode2"=>"VC", "kode3"=>"VCT", "nkode"=>"670", "ean1"=>"", "ean2"=>"", "olimp"=>"VIN", "fut"=>"VIN",),
    "сент-китс и невис" =>  array("name"=>"Сент-Китс и Невис", "phone"=>"1 869", "kode2"=>"KN", "kode3"=>"KNA", "nkode"=>"659", "ean1"=>"", "ean2"=>"", "olimp"=>"SKN", "fut"=>"SKN",),
    "сент-люсия" =>  array("name"=>"Сент-Люсия", "phone"=>"1 758", "kode2"=>"LC", "kode3"=>"LCA", "nkode"=>"662", "ean1"=>"", "ean2"=>"", "olimp"=>"LCA", "fut"=>"LCA",),
    "сербия" =>  array("name"=>"Сербия", "phone"=>"381", "kode2"=>"RS", "kode3"=>"SRB", "nkode"=>"688", "ean1"=>"860", "ean2"=>"860", "olimp"=>"SRB", "fut"=>"SRB",),
    "сингапур" =>  array("name"=>"Сингапур", "phone"=>"65", "kode2"=>"SG", "kode3"=>"SGP", "nkode"=>"702", "ean1"=>"888", "ean2"=>"888", "olimp"=>"SIN", "fut"=>"SIN",),
    "сирия" =>  array("name"=>"Сирия", "phone"=>"963", "kode2"=>"SY", "kode3"=>"SYR", "nkode"=>"760", "ean1"=>"621", "ean2"=>"621", "olimp"=>"SYR", "fut"=>"SYR",),
    "словакия" =>  array("name"=>"Словакия", "phone"=>"421", "kode2"=>"SK", "kode3"=>"SVK", "nkode"=>"703", "ean1"=>"858", "ean2"=>"858", "olimp"=>"SVK", "fut"=>"SVK",),
    "словения" =>  array("name"=>"Словения", "phone"=>"386", "kode2"=>"SI", "kode3"=>"SVN", "nkode"=>"705", "ean1"=>"383", "ean2"=>"383", "olimp"=>"SLO", "fut"=>"SVN",),
    "соломоновы острова" =>  array("name"=>"Соломоновы Острова", "phone"=>"677", "kode2"=>"SB", "kode3"=>"SLB", "nkode"=>"90", "ean1"=>"", "ean2"=>"", "olimp"=>"SOL", "fut"=>"SOL",),
    "сомали" =>  array("name"=>"Сомали", "phone"=>"252", "kode2"=>"SO", "kode3"=>"SOM", "nkode"=>"706", "ean1"=>"", "ean2"=>"", "olimp"=>"SOM", "fut"=>"SOM",),
    "судан" =>  array("name"=>"Судан", "phone"=>"249", "kode2"=>"SD", "kode3"=>"SDN", "nkode"=>"729", "ean1"=>"", "ean2"=>"", "olimp"=>"SUD", "fut"=>"SDN",),
    "суринам" =>  array("name"=>"Суринам", "phone"=>"597", "kode2"=>"SR", "kode3"=>"SUR", "nkode"=>"740", "ean1"=>"", "ean2"=>"", "olimp"=>"SUR", "fut"=>"SUR",),
    "сша" =>  array("name"=>"США", "phone"=>"+1 xxx", "kode2"=>"US", "kode3"=>"USA", "nkode"=>"840", "ean1"=>"0", "ean2"=>"139", "olimp"=>"USA", "fut"=>"USA",),
    "сьерра-леоне" =>  array("name"=>"Сьерра-Леоне", "phone"=>"232", "kode2"=>"SL", "kode3"=>"SLE", "nkode"=>"694", "ean1"=>"", "ean2"=>"", "olimp"=>"SLE", "fut"=>"SLE",),
    "таджикистан" =>  array("name"=>"Таджикистан", "phone"=>"992", "kode2"=>"TJ", "kode3"=>"TJK", "nkode"=>"762", "ean1"=>"488", "ean2"=>"488", "olimp"=>"TJK", "fut"=>"TJK",),
    "таиланд" =>  array("name"=>"Таиланд", "phone"=>"66", "kode2"=>"TH", "kode3"=>"THA", "nkode"=>"764", "ean1"=>"885", "ean2"=>"885", "olimp"=>"THA", "fut"=>"THA",),
    "танзания" =>  array("name"=>"Танзания", "phone"=>"255", "kode2"=>"TZ", "kode3"=>"TZA", "nkode"=>"834", "ean1"=>"", "ean2"=>"", "olimp"=>"TAN", "fut"=>"TAN",),
    "того" =>  array("name"=>"Того", "phone"=>"228", "kode2"=>"TG", "kode3"=>"TGO", "nkode"=>"768", "ean1"=>"", "ean2"=>"", "olimp"=>"TOG", "fut"=>"TOG",),
    "тонга" =>  array("name"=>"Тонга", "phone"=>"676", "kode2"=>"TO", "kode3"=>"TON", "nkode"=>"776", "ean1"=>"", "ean2"=>"", "olimp"=>"TGA", "fut"=>"TGA",),
    "тринидад и тобаго" =>  array("name"=>"Тринидад и Тобаго", "phone"=>"1 868", "kode2"=>"TT", "kode3"=>"TTO", "nkode"=>"780", "ean1"=>"", "ean2"=>"", "olimp"=>"TRI", "fut"=>"TRI",),
    "тувалу" =>  array("name"=>"Тувалу", "phone"=>"688", "kode2"=>"TV", "kode3"=>"TUV", "nkode"=>"798", "ean1"=>"", "ean2"=>"", "olimp"=>"TUV", "fut"=>"-",),
    "тунис" =>  array("name"=>"Тунис", "phone"=>"216", "kode2"=>"TN", "kode3"=>"TUN", "nkode"=>"788", "ean1"=>"619", "ean2"=>"619", "olimp"=>"TUN", "fut"=>"TUN",),
    "туркмения" =>  array("name"=>"Туркмения", "phone"=>"993", "kode2"=>"TM", "kode3"=>"TKM", "nkode"=>"795", "ean1"=>"", "ean2"=>"", "olimp"=>"TKM", "fut"=>"TKM",),
    "турция" =>  array("name"=>"Турция", "phone"=>"90", "kode2"=>"TR", "kode3"=>"TUR", "nkode"=>"792", "ean1"=>"869", "ean2"=>"869", "olimp"=>"TUR", "fut"=>"TUR",),
    "уганда" =>  array("name"=>"Уганда", "phone"=>"256", "kode2"=>"UG", "kode3"=>"UGA", "nkode"=>"800", "ean1"=>"", "ean2"=>"", "olimp"=>"UGA", "fut"=>"UGA",),
    "узбекистан" =>  array("name"=>"Узбекистан", "phone"=>"998", "kode2"=>"UZ", "kode3"=>"UZB", "nkode"=>"860", "ean1"=>"478", "ean2"=>"478", "olimp"=>"UZB", "fut"=>"UZB",),
    "украина" =>  array("name"=>"Украина", "phone"=>"380", "kode2"=>"UA", "kode3"=>"UKR", "nkode"=>"804", "ean1"=>"482", "ean2"=>"482", "olimp"=>"UKR", "fut"=>"UKR",),
    "уругвай" =>  array("name"=>"Уругвай", "phone"=>"598", "kode2"=>"UY", "kode3"=>"URY", "nkode"=>"858", "ean1"=>"773", "ean2"=>"773", "olimp"=>"URU", "fut"=>"URU",),
    "федеративные штаты микронезии" =>  array("name"=>"Федеративные Штаты Микронезии", "phone"=>"691", "kode2"=>"FM", "kode3"=>"FSM", "nkode"=>"583", "ean1"=>"", "ean2"=>"", "olimp"=>"FSM", "fut"=>"-",),
    "фиджи" =>  array("name"=>"Фиджи", "phone"=>"679", "kode2"=>"FJ", "kode3"=>"FJI", "nkode"=>"242", "ean1"=>"", "ean2"=>"", "olimp"=>"FIJ", "fut"=>"FIJ",),
    "филиппины" =>  array("name"=>"Филиппины", "phone"=>"63", "kode2"=>"PH", "kode3"=>"PHL", "nkode"=>"608", "ean1"=>"480", "ean2"=>"480", "olimp"=>"PHI", "fut"=>"PHI",),
    "финляндия" =>  array("name"=>"Финляндия", "phone"=>"358", "kode2"=>"FI", "kode3"=>"FIN", "nkode"=>"246", "ean1"=>"640", "ean2"=>"649", "olimp"=>"FIN", "fut"=>"FIN",),
    "франция" =>  array("name"=>"Франция", "phone"=>"33", "kode2"=>"FR", "kode3"=>"FRA", "nkode"=>"250", "ean1"=>"300", "ean2"=>"379", "olimp"=>"FRA", "fut"=>"FRA",),
    "хорватия" =>  array("name"=>"Хорватия", "phone"=>"385", "kode2"=>"HR", "kode3"=>"HRV", "nkode"=>"191", "ean1"=>"385", "ean2"=>"385", "olimp"=>"CRO", "fut"=>"CRO",),
    "цар" =>  array("name"=>"ЦАР", "phone"=>"236", "kode2"=>"CF", "kode3"=>"CAF", "nkode"=>"140", "ean1"=>"", "ean2"=>"", "olimp"=>"CAF", "fut"=>"CTA",),
    "чад" =>  array("name"=>"Чад", "phone"=>"235", "kode2"=>"TD", "kode3"=>"TCD", "nkode"=>"148", "ean1"=>"", "ean2"=>"", "olimp"=>"CHA", "fut"=>"CHA",),
    "черногория" =>  array("name"=>"Черногория", "phone"=>"382", "kode2"=>"ME", "kode3"=>"MNE", "nkode"=>"499", "ean1"=>"860", "ean2"=>"860", "olimp"=>"MNE", "fut"=>"MNE",),
    "чехия" =>  array("name"=>"Чехия", "phone"=>"420", "kode2"=>"CZ", "kode3"=>"CZE", "nkode"=>"203", "ean1"=>"859", "ean2"=>"859", "olimp"=>"CZE", "fut"=>"CZE",),
    "чили" =>  array("name"=>"Чили", "phone"=>"56", "kode2"=>"CL", "kode3"=>"CHL", "nkode"=>"152", "ean1"=>"780", "ean2"=>"780", "olimp"=>"CHI", "fut"=>"CHI",),
    "швейцария" =>  array("name"=>"Швейцария", "phone"=>"41", "kode2"=>"CH", "kode3"=>"CHE", "nkode"=>"756", "ean1"=>"760", "ean2"=>"769", "olimp"=>"SUI", "fut"=>"SUI",),
    "швеция" =>  array("name"=>"Швеция", "phone"=>"46", "kode2"=>"SE", "kode3"=>"SWE", "nkode"=>"752", "ean1"=>"730", "ean2"=>"739", "olimp"=>"SWE", "fut"=>"SWE",),
    "шри-ланка" =>  array("name"=>"Шри-Ланка", "phone"=>"94", "kode2"=>"LK", "kode3"=>"LKA", "nkode"=>"144", "ean1"=>"479", "ean2"=>"479", "olimp"=>"SRI", "fut"=>"SRI",),
    "эквадор" =>  array("name"=>"Эквадор", "phone"=>"593", "kode2"=>"EC", "kode3"=>"ECU", "nkode"=>"218", "ean1"=>"786", "ean2"=>"786", "olimp"=>"ECU", "fut"=>"ECU",),
    "экваториальная гвинея" =>  array("name"=>"Экваториальная Гвинея", "phone"=>"240", "kode2"=>"GQ", "kode3"=>"GNQ", "nkode"=>"226", "ean1"=>"", "ean2"=>"", "olimp"=>"GEQ", "fut"=>"EQG",),
    "эритрея" =>  array("name"=>"Эритрея", "phone"=>"291", "kode2"=>"ER", "kode3"=>"ERI", "nkode"=>"232", "ean1"=>"", "ean2"=>"", "olimp"=>"ERI", "fut"=>"ERI",),
    "эстония" =>  array("name"=>"Эстония", "phone"=>"372", "kode2"=>"EE", "kode3"=>"EST", "nkode"=>"233", "ean1"=>"474", "ean2"=>"474", "olimp"=>"EST", "fut"=>"EST",),
    "эфиопия" =>  array("name"=>"Эфиопия", "phone"=>"251", "kode2"=>"ET", "kode3"=>"ETH", "nkode"=>"231", "ean1"=>"", "ean2"=>"", "olimp"=>"ETH", "fut"=>"ETH",),
    "юар" =>  array("name"=>"ЮАР", "phone"=>"27", "kode2"=>"ZA", "kode3"=>"ZAF", "nkode"=>"710", "ean1"=>"600", "ean2"=>"601", "olimp"=>"RSA", "fut"=>"RSA",),
    "южная осетия" =>  array("name"=>"Южная Осетия", "phone"=>"+7 xxx", "kode2"=>"OS", "kode3"=>"OST", "nkode"=>"896", "ean1"=>"", "ean2"=>"", "olimp"=>"-", "fut"=>"-",),
    "южный судан" =>  array("name"=>"Южный Судан", "phone"=>"211", "kode2"=>"SS", "kode3"=>"SSD", "nkode"=>"728", "ean1"=>"", "ean2"=>"", "olimp"=>"-", "fut"=>"SSD",),
    "ямайка" =>  array("name"=>"Ямайка", "phone"=>"1 876", "kode2"=>"JM", "kode3"=>"JAM", "nkode"=>"388", "ean1"=>"", "ean2"=>"", "olimp"=>"JAM", "fut"=>"JAM",),
    "япония" =>  array("name"=>"Япония", "phone"=>"81", "kode2"=>"JP", "kode3"=>"JPN", "nkode"=>"392", "ean1"=>"490", "ean2"=>"499", "olimp"=>"JPN", "fut"=>"JPN",),

);
